org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# Project metadata
archives_base_name=cobblemon-move-tutor
mod_id=cobblemon_move_tutor
mod_version=1.2.0-SNAPSHOT
maven_group=dev.matthiesen
mod_name=Cobblemon Move Tutor
mod_description=A Cobblemon side mod that adds a move tutor to the game.
mod_license=MIT License
mod_license_url=https://github.com/Matthiesen-dev/cobblemon-move-tutor/blob/main/LICENSE
mod_author=Adam Matthiesen
mod_author_id=adammatthiesen
mod_author_url=https://github.com/Adammatthiesen
github_url=https://github.com/Matthiesen-dev/cobblemon-move-tutor
modrinth_url=https://modrinth.com/mod/cobblemon-move-tutor

minecraft_version=1.21.1

# Build-logic versions still consumed from properties
junit_version=5.1.0
