name: Publish Release to Modrinth

on:
  release:
    types: [ published ]

# The dependencies above correspond to:
# - Cobblemon (MdwFAVRL)
# - Matthiesen Core (sqEZOmQo)
# - CobbleDollars (s7N7AsqL)
# - Impactor (LdBYVaPS)
## Fabric Only:
# - Fabric API (P7dR8mSH) - Required
# - ForgeConfigAPI Port (ohNO6lps) - Required

jobs:
  publish:
    uses: matthiesen-dev/automation/.github/workflows/simple-publish.yml@main
    permissions:
      contents: write
    with:
      tag_name: ${{ github.event.release.tag_name }}
      artifact_basename: "cobblemon-move-tutor"
      mod_name: "Cobblemon Move Tutor"
      changelog: ${{ github.event.release.body }}
      fabric_loader_version: "0.17.2+"
      neoforge_loader_version: "21.1.182+"
      modrinth_game_version: "1.21.1"
      modrinth_id: "1AYwVfn9"
      modrinth_dependencies: |-
        [
          {"project_id":"MdwFAVRL","dependency_type":"required"},
          {"project_id":"sqEZOmQo","dependency_type":"required"},
          {"project_id":"s7N7AsqL","dependency_type":"optional"},
          {"project_id":"LdBYVaPS","dependency_type":"optional"}
        ]
      modrinth_fabric_dependencies: |-
        [
          {"project_id":"P7dR8mSH","dependency_type":"required"},
          {"project_id":"ohNO6lps","dependency_type":"required"}
        ]
      discord_icon_url: "https://raw.githubusercontent.com/Matthiesen-dev/.github/refs/heads/main/mod-logos/cobblemon-move-tutor.png"
    secrets:
      git_token: ${{ secrets.GITHUB_TOKEN }}
      MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}